config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :categories, only: [:index, :show] do
    resources :products, only: [:new, :create] do
      resources :reviews, only: [:new, :create]
    end
  end
      resources :products, only:[:show, :edit, :update, :destroy]
      resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :products
  has_one_attached :photo
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :rating, inclusion: {in: [1, 2, 3, 4, 5], allow_nil: false}
  has_many_attached :photos
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates :content, presence: true, length: {minimum: 20}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # before_action :configure_permitted_parameters, if: :devise_controller?
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @product = Product.new
  end

private

  def category_params
    params.require(:article).permit(:name, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :new, :create]

  def show
    # @category = Category.find(params[:category_id])
    @product = Product.find(params[:id])
  end

  def new
    @category = Category.find(params[:category_id])
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    # we need `category_id` to associate product with corresponding category
    @category = Category.find(params[:category_id])
    @product.category = @category
    if @product.save
      redirect_to category_path(@category)
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @category = Category.find(params[:category_id])
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @category = @product.category
    @product.destroy
    redirect_to category_path(@product.category)
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :rating, photos: [])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(category) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
<% end %>

app/views/categories/index.html.erb
<div class="container-top">
  <div>
    <center><h2 class="mt-4">Marshmallows for all occassions 🍭 🎂 🍬 </h2></center>
  </div>
  <div class = "container categories">
    <% @categories.each do |category| %>
      <div class="card-category p-4" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= image_path "somuchfun.jpg" %>)">
        <div class="category-info">
          <h2 class="category-title"><%= link_to category.name, category_path(category.id), class: "category-link" %></h2>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="container products">
  <div class="rounded p-4 mt-3">
    <center><h2 class="mt-4"><%= @category.name %></h2></center>
    <% @category.products.each do |product| %>
      <div class="card-product">
          <% if product.photos.attached?%>
            <%= cl_image_tag product.photos.first.key, crop: :fill %>
          <% end %>
        <div class="card-product-infos">
        <h5 class="mt-3"><%= link_to product.name, product_path(product) %></h5>
          <p><%= product.description %></p>
          <p>£ <%= product.price %>.00</p>
          <p>Rating: <%= product.rating %> ⭐️⭐️⭐️⭐️</p>
          <%= link_to "", edit_product_path(product), class: "fas fa-edit"%>
          <%= link_to "", product_path(product), method: :delete, data: {confirm: "Are you sure?"}, class: "far fa-trash-alt" %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="container">
    <div class="rounded bg-primary p-4 mt-3">
      <%= link_to "Add a new product", new_category_product_path(@category), class: "btn btn-primary"  %><br>
      <%= link_to 'Back', categories_path, class: "btn btn-primary"  %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdrianaSMarshmallows</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <!-- <p class="alert"><%= alert %></p> -->
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.2)), url(<%= image_path "muffin.jpg" %>);">
  <div class="container text-light">
    <h1>Delicious <strong class="text-home">Adriana's Marshmallows.</strong>
    <h3>Unique, home made Marshmallows and for special occassions or an extra treat for your guests or just for yourself.</h3><br>
    <p>
      <span id="banner-typed-text"></span>
    </p>
    <h4>🍭 Sweet <strong class="text-home">🍭 Sweet 🍭</strong> Selection! 🍭 </h4><br>

    <%= link_to "Search for marshmallows", categories_path, class: "btn btn-primary" %>
  </div>
</div>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12">
      <%= "Why do small treats matter? When we feel depleted and drained, and when we have no time or energy left to devote to little activities that give us pleasure, we start to feel exhausted, resentful, and angry. Indulging in a small treat helps refresh and energize us. G.R." * 20 %>
    </div>
  </div>
</div>

<!-- Footer -->
<div class="footer">
<p>Follow us on:</p>
  <div class="footer-links">
    <a href="https://www.instagram.com/adrianasmarshmallows/?hl=en"><i class="fab fa-instagram"></i> Instagram</a>
    <a href="https://www.facebook.com/adrianasmarshmallows"><i class="fab fa-facebook"></i> Facebook</a>
  </div>
</div>

app/views/products/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <%= simple_form_for [@category, @product] do |f| %>
        <div class="form-inputs">
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.input :price %>
          <%= f.input :rating %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <%= f.submit "Submit product", class: "btn btn-pink" %>
          <%= link_to 'Back', categories_path, class: "btn btn-primary"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<%= render "form", category: @category, product: @product %>

app/views/products/new.html.erb
<%= render "form", category: @category, product: @product %>

app/views/products/show.html.erb
<div class="container">
  <h1><%= @product.name %></h1>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top mb-8px">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.jpg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", "#", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Categories", categories_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "basket.png", class: "basket dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Basket", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>